/**
 * SupportDesk Agent Feature — Isolated Mock Data
 */

export const currentAgent = {
  id: 'agt_201',
  name: 'Alex Johnson',
  email: 'alex.johnson@supportdesk.com',
  role: 'Support Agent',
  initials: 'AJ',
  department: 'Tier 2 Technical Support',
  team: 'Core Platform & Integrations',
  availability: 'Available', // 'Available' | 'Busy' | 'Away' | 'Offline'
  unreadNotificationsCount: 4,
  categories: ['Technical', 'Account', 'Billing', 'Integrations'],
};

export const agentDashboardKPIs = [
  {
    id: 'assigned',
    label: 'Assigned to Me',
    value: 18,
    change: '+3 today',
    trend: 'up',
    color: '#0A84FF',
    bgColor: 'rgba(10, 132, 255, 0.12)',
    icon: 'user-check',
  },
  {
    id: 'in_progress',
    label: 'In Progress',
    value: 7,
    change: '2 high priority',
    trend: 'neutral',
    color: '#64D2FF',
    bgColor: 'rgba(100, 210, 255, 0.12)',
    icon: 'clock',
  },
  {
    id: 'waiting',
    label: 'Waiting for Customer',
    value: 5,
    change: 'Need customer response',
    trend: 'neutral',
    color: '#FFD60A',
    bgColor: 'rgba(255, 214, 10, 0.12)',
    icon: 'hourglass',
  },
  {
    id: 'at_risk',
    label: 'SLA At Risk',
    value: 3,
    change: 'Needs attention',
    trend: 'down',
    color: '#FF9F0A',
    bgColor: 'rgba(255, 159, 10, 0.12)',
    icon: 'alert-triangle',
  },
  {
    id: 'overdue',
    label: 'Overdue',
    value: 2,
    change: 'Requires action',
    trend: 'down',
    color: '#FF453A',
    bgColor: 'rgba(255, 69, 58, 0.12)',
    icon: 'x-circle',
  },
  {
    id: 'resolved_today',
    label: 'Resolved Today',
    value: 12,
    change: '+20% vs yesterday',
    trend: 'up',
    color: '#30D158',
    bgColor: 'rgba(48, 209, 88, 0.12)',
    icon: 'check-circle',
  },
];

export const myQueueTickets = [
  {
    id: '#1024',
    subject: 'Unable to access account',
    customer: 'Rahul Sharma',
    customerEmail: 'rahul.sharma@company.com',
    category: 'Account',
    priority: 'High',
    priorityVariant: 'high',
    status: 'In Progress',
    statusVariant: 'info',
    sla: '42 min remaining',
    slaStatus: 'normal',
    updated: '5 min ago',
    created: 'Today, 10:32 AM',
  },
  {
    id: '#1021',
    subject: 'Payment failed during checkout',
    customer: 'Anjali Menon',
    customerEmail: 'anjali@paytech.com',
    category: 'Billing',
    priority: 'Medium',
    priorityVariant: 'medium',
    status: 'Waiting for Customer',
    statusVariant: 'warning',
    sla: '2h 15m remaining',
    slaStatus: 'normal',
    updated: '18 min ago',
    created: 'Today, 09:15 AM',
  },
  {
    id: '#1018',
    subject: 'Application crashes on startup',
    customer: 'Arun Kumar',
    customerEmail: 'arun.k@devstudio.io',
    category: 'Technical',
    priority: 'Critical',
    priorityVariant: 'critical',
    status: 'In Progress',
    statusVariant: 'info',
    sla: '18 min remaining',
    slaStatus: 'at_risk',
    updated: '4 min ago',
    created: 'Today, 08:45 AM',
  },
  {
    id: '#1015',
    subject: 'Password reset link expired',
    customer: 'Meera Iyer',
    customerEmail: 'meera.i@designco.com',
    category: 'Account',
    priority: 'Low',
    priorityVariant: 'low',
    status: 'Open',
    statusVariant: 'open',
    sla: '5h remaining',
    slaStatus: 'normal',
    updated: '1 hour ago',
    created: 'Yesterday, 04:20 PM',
  },
  {
    id: '#1009',
    subject: 'Unable to complete payment process',
    customer: 'Vikram Singh',
    customerEmail: 'vikram@enterprises.com',
    category: 'Billing',
    priority: 'High',
    priorityVariant: 'high',
    status: 'Waiting for Customer',
    statusVariant: 'warning',
    sla: '12 min remaining (At Risk)',
    slaStatus: 'at_risk',
    updated: '2 hours ago',
    created: 'Yesterday, 02:10 PM',
  },
];

export const slaOverviewStats = {
  total: 19,
  withinSLA: 14,
  atRisk: 3,
  breached: 2,
};

export const needsAttentionList = [
  {
    id: '#1018',
    subject: 'Application crashes on startup',
    priority: 'Critical',
    priorityColor: '#FF453A',
    timeRemaining: '18 minutes remaining',
    badge: 'SLA Urgent',
  },
  {
    id: '#1009',
    subject: 'Customer unable to complete payment',
    priority: 'High',
    priorityColor: '#FF9F0A',
    timeRemaining: '12 minutes remaining',
    badge: 'At Risk',
  },
  {
    id: '#1004',
    subject: 'Production login failure',
    priority: 'Critical',
    priorityColor: '#FF453A',
    timeRemaining: 'SLA Breached',
    badge: 'Escalated',
  },
];

export const workloadChartData = {
  days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
  assigned: [8, 12, 15, 10, 18, 5, 3],
  resolved: [7, 10, 14, 9, 12, 4, 2],
};

export const agentRecentActivity = [
  {
    id: 'act_1',
    text: 'Ticket #1021 assigned to you',
    time: '5 minutes ago',
    type: 'assignment',
  },
  {
    id: 'act_2',
    text: 'Customer Rahul Sharma replied to ticket #1018',
    time: '12 minutes ago',
    type: 'reply',
  },
  {
    id: 'act_3',
    text: 'Ticket #1015 marked as resolved',
    time: '28 minutes ago',
    type: 'resolution',
  },
  {
    id: 'act_4',
    text: 'Ticket #1009 escalated to Tier 3 Support',
    time: '42 minutes ago',
    type: 'escalation',
  },
];

export const allAgentTicketsList = [
  ...myQueueTickets,
  {
    id: '#1023',
    subject: 'Email notifications not working',
    customer: 'David Wright',
    customerEmail: 'david.w@techcorp.com',
    category: 'Technical',
    assignedAgent: 'Sarah Chen',
    priority: 'Medium',
    priorityVariant: 'medium',
    status: 'In Progress',
    statusVariant: 'info',
    sla: '1h 30m remaining',
    slaStatus: 'normal',
    updated: '30 min ago',
    created: 'Today, 09:40 AM',
  },
  {
    id: '#1022',
    subject: 'API Gateway 504 Gateway Timeout',
    customer: 'DevOps Team',
    customerEmail: 'devops@cloudservices.io',
    category: 'Integrations',
    assignedAgent: 'David Miller',
    priority: 'Critical',
    priorityVariant: 'critical',
    status: 'Open',
    statusVariant: 'open',
    sla: '45 min remaining',
    slaStatus: 'normal',
    updated: '40 min ago',
    created: 'Today, 09:20 AM',
  },
  {
    id: '#1020',
    subject: 'Bulk CSV export fails on 10k rows',
    customer: 'Data Analytics Co',
    customerEmail: 'analytics@dataco.org',
    category: 'Technical',
    assignedAgent: 'Unassigned',
    priority: 'Low',
    priorityVariant: 'low',
    status: 'Open',
    statusVariant: 'open',
    sla: '6h remaining',
    slaStatus: 'normal',
    updated: '2 hours ago',
    created: 'Today, 07:30 AM',
  },
  {
    id: '#1004',
    subject: 'Production login failure',
    customer: 'Enterprise Client Inc',
    customerEmail: 'admin@enterprise.com',
    category: 'Account',
    assignedAgent: 'Alex Johnson',
    priority: 'Critical',
    priorityVariant: 'critical',
    status: 'In Progress',
    statusVariant: 'info',
    sla: 'Breached (15m ago)',
    slaStatus: 'breached',
    updated: '10 min ago',
    created: 'Yesterday, 11:00 AM',
  },
];

export const escalatedTicketsList = [
  {
    id: '#1004',
    subject: 'Production login failure',
    customer: 'Enterprise Client Inc',
    priority: 'Critical',
    reason: 'Production impact',
    assignedAgent: 'Alex Johnson',
    sla: 'Breached (15m ago)',
    updated: '10 min ago',
    details: 'Production SSO OAuth endpoint returning HTTP 500 error across all enterprise tenants.',
  },
  {
    id: '#1009',
    subject: 'Customer unable to complete payment',
    customer: 'Vikram Singh',
    priority: 'High',
    reason: 'SLA risk',
    assignedAgent: 'Alex Johnson',
    sla: '12 min remaining',
    updated: '2 hours ago',
    details: 'Stripe webhook listener dropping signature validation tokens.',
  },
  {
    id: '#1002',
    subject: 'Webhook integration timeout on payload > 2MB',
    customer: 'TechCorp Inc',
    priority: 'Critical',
    reason: 'Technical complexity',
    assignedAgent: 'Sarah Chen',
    sla: 'At Risk (8m left)',
    updated: '1 hour ago',
    details: 'Requires engineering patch to increase payload buffer size on gateway routers.',
  },
  {
    id: '#998',
    subject: 'Enterprise SSO SAML 2.0 cert expiration',
    customer: 'Global Systems LLC',
    priority: 'Critical',
    reason: 'Requires higher-level access',
    assignedAgent: 'David Miller',
    sla: 'Breached (1h ago)',
    updated: '3 hours ago',
    details: 'Root CA certificate renewal requires Security Admin privileges.',
  },
];

export const sampleTicketDetails = {
  id: '#1024',
  subject: 'Unable to access account after changing password',
  customer: {
    name: 'Rahul Sharma',
    email: 'rahul.sharma@company.com',
    avatar: 'RS',
    company: 'Acme Corp',
  },
  category: 'Account',
  priority: 'High',
  status: 'In Progress',
  assignedAgent: 'Alex Johnson',
  created: 'Today, 10:32 AM',
  updated: '5 minutes ago',
  slaTimeRemaining: '42 minutes remaining',
  slaStatus: 'normal',
  conversation: [
    {
      id: 'msg_1',
      sender: 'customer',
      senderName: 'Rahul Sharma',
      time: '10:32 AM',
      text: "I'm unable to access my account after changing my password this morning. It shows an invalid credentials error even though I used the password generator.",
      attachments: [
        { name: 'error-screenshot.png', size: '324 KB', type: 'image' },
      ],
    },
    {
      id: 'msg_2',
      sender: 'agent',
      senderName: 'Alex Johnson (Support Agent)',
      time: '10:45 AM',
      text: "Hi Rahul, thank you for reaching out. I am looking into your account session tokens right now. Could you please confirm if you have active sessions on multiple browsers or devices?",
      attachments: [],
    },
    {
      id: 'msg_3',
      sender: 'customer',
      senderName: 'Rahul Sharma',
      time: '11:02 AM',
      text: 'Yes, I am logged in on my iPhone app and my Chrome browser on MacOS.',
      attachments: [],
    },
  ],
  internalNotes: [
    {
      id: 'note_1',
      author: 'Alex Johnson',
      time: '10:48 AM',
      text: 'Checked auth log buffer: Customer account triggered brute-force rate limit (5 invalid token attempts). Need to flush redis session cache for user usr_101.',
    },
  ],
  timeline: [
    { event: 'Ticket created by Rahul Sharma', time: '10:32 AM' },
    { event: 'Assigned to Alex Johnson', time: '10:35 AM' },
    { event: 'Priority escalated to High', time: '10:40 AM' },
    { event: 'Agent Alex Johnson replied', time: '10:45 AM' },
    { event: 'Customer Rahul Sharma replied', time: '11:02 AM' },
  ],
};

export const agentNotificationsList = [
  {
    id: 'notif_agt_1',
    title: 'Ticket #1021 assigned to you',
    subtitle: 'Payment failed during checkout',
    time: '5 minutes ago',
    unread: true,
    targetRoute: '/agent/tickets/1021',
    type: 'assignment',
  },
  {
    id: 'notif_agt_2',
    title: 'Customer Rahul Sharma replied to Ticket #1018',
    subtitle: 'Application crashes on startup',
    time: '12 minutes ago',
    unread: true,
    targetRoute: '/agent/tickets/1018',
    type: 'reply',
  },
  {
    id: 'notif_agt_3',
    title: 'SLA Warning: Ticket #1009 is at risk',
    subtitle: '12 minutes remaining before SLA breach',
    time: '25 minutes ago',
    unread: true,
    targetRoute: '/agent/tickets/1009',
    type: 'sla_warning',
  },
  {
    id: 'notif_agt_4',
    title: 'Ticket #1004 escalated to Tier 3',
    subtitle: 'Production login failure requires Security Admin access',
    time: '42 minutes ago',
    unread: true,
    targetRoute: '/agent/tickets/1004',
    type: 'escalation',
  },
  {
    id: 'notif_agt_5',
    title: 'Ticket #1015 marked as resolved',
    subtitle: 'Password reset issue completed',
    time: '1 hour ago',
    unread: false,
    targetRoute: '/agent/tickets/1015',
    type: 'resolution',
  },
];
