/**
 * SupportDesk Admin Feature — Centralized Mock Data
 * System-wide operational data for Administrator workflows.
 */

export const currentAdmin = {
  id: 'adm_001',
  name: 'Alex Rivera',
  email: 'admin@supportdesk.com',
  role: 'System Administrator',
  initials: 'AR',
  unreadNotificationsCount: 5,
};

export const adminDashboardKPIs = [
  {
    id: 'total_tickets',
    label: 'Total Tickets',
    value: '1,248',
    change: '+12% this month',
    trend: 'up',
    color: '#0A84FF',
    bgColor: 'rgba(10, 132, 255, 0.12)',
    icon: 'layers',
  },
  {
    id: 'open_tickets',
    label: 'Open Tickets',
    value: '186',
    change: '24 high priority',
    trend: 'neutral',
    color: '#64D2FF',
    bgColor: 'rgba(100, 210, 255, 0.12)',
    icon: 'folder-open',
  },
  {
    id: 'in_progress',
    label: 'In Progress',
    value: '74',
    change: 'Across all agents',
    trend: 'neutral',
    color: '#FFD60A',
    bgColor: 'rgba(255, 214, 10, 0.12)',
    icon: 'clock',
  },
  {
    id: 'at_risk',
    label: 'SLA At Risk',
    value: '18',
    change: 'Needs attention',
    trend: 'down',
    color: '#FF9F0A',
    bgColor: 'rgba(255, 159, 10, 0.12)',
    icon: 'alert-triangle',
  },
  {
    id: 'overdue',
    label: 'Overdue',
    value: '7',
    change: 'Requires action',
    trend: 'down',
    color: '#FF453A',
    bgColor: 'rgba(255, 69, 58, 0.12)',
    icon: 'x-circle',
  },
  {
    id: 'resolved_month',
    label: 'Resolved This Month',
    value: '981',
    change: '+8% vs last month',
    trend: 'up',
    color: '#30D158',
    bgColor: 'rgba(48, 209, 88, 0.12)',
    icon: 'check-circle',
  },
];

export const adminSystemStats = {
  activeCustomers: 452,
  activeAgents: 12,
  totalCategories: 8,
  activeSLAPolicies: 4,
};

export const adminTicketActivityData = {
  '7d': {
    days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    created: [42, 58, 65, 51, 74, 22, 18],
    resolved: [38, 52, 60, 48, 68, 25, 15],
  },
  '30d': {
    days: ['Week 1', 'Week 2', 'Week 3', 'Week 4'],
    created: [310, 285, 340, 313],
    resolved: [295, 278, 325, 283],
  },
  '90d': {
    days: ['Month 1', 'Month 2', 'Month 3'],
    created: [1120, 1190, 1248],
    resolved: [1080, 1140, 1184],
  },
};

export const adminStatusDistribution = [
  { status: 'Open', count: 186, color: '#0A84FF', percentage: '15%' },
  { status: 'In Progress', count: 74, color: '#64D2FF', percentage: '6%' },
  { status: 'Waiting for Customer', count: 42, color: '#FFD60A', percentage: '3%' },
  { status: 'Resolved', count: 840, color: '#30D158', percentage: '67%' },
  { status: 'Closed', count: 106, color: '#6b7280', percentage: '9%' },
];

export const adminPriorityDistribution = [
  { priority: 'Critical', count: 28, color: '#FF453A', percentage: '2%' },
  { priority: 'High', count: 142, color: '#FF9F0A', percentage: '11%' },
  { priority: 'Medium', count: 520, color: '#FFD60A', percentage: '42%' },
  { priority: 'Low', count: 558, color: '#30D158', percentage: '45%' },
];

export const adminSlaOverviewStats = {
  total: 1248,
  withinSLA: 1223,
  atRisk: 18,
  breached: 7,
};

export const adminAgentOperationalOverview = [
  {
    id: 'agt_201',
    agent: 'Alex Johnson',
    email: 'alex.johnson@supportdesk.com',
    assigned: 24,
    inProgress: 7,
    resolved: 18,
    pending: 6,
    sla: '96%',
    status: 'Available',
  },
  {
    id: 'agt_202',
    agent: 'Sarah Wilson',
    email: 'sarah.wilson@supportdesk.com',
    assigned: 21,
    inProgress: 6,
    resolved: 17,
    pending: 4,
    sla: '94%',
    status: 'Busy',
  },
  {
    id: 'agt_203',
    agent: 'Daniel Thomas',
    email: 'daniel.thomas@supportdesk.com',
    assigned: 19,
    inProgress: 5,
    resolved: 15,
    pending: 4,
    sla: '91%',
    status: 'Available',
  },
  {
    id: 'agt_204',
    agent: 'Michael Chang',
    email: 'michael.chang@supportdesk.com',
    assigned: 18,
    inProgress: 4,
    resolved: 14,
    pending: 4,
    sla: '98%',
    status: 'Away',
  },
  {
    id: 'agt_205',
    agent: 'Elena Rostova',
    email: 'elena.rostova@supportdesk.com',
    assigned: 15,
    inProgress: 3,
    resolved: 12,
    pending: 3,
    sla: '95%',
    status: 'Offline',
  },
];

export const adminRecentTickets = [
  {
    id: '#1024',
    subject: 'Unable to access account',
    customer: 'Rahul Sharma',
    customerEmail: 'rahul.sharma@company.com',
    agent: 'Alex Johnson',
    category: 'Account & Access',
    priority: 'High',
    status: 'In Progress',
    sla: '42 min remaining',
    updated: '5 min ago',
    created: 'Today, 10:32 AM',
  },
  {
    id: '#1021',
    subject: 'Payment failed during checkout',
    customer: 'Anjali Menon',
    customerEmail: 'anjali@paytech.com',
    agent: 'Sarah Wilson',
    category: 'Payments',
    priority: 'Medium',
    status: 'Waiting for Customer',
    sla: '2h 15m remaining',
    updated: '18 min ago',
    created: 'Today, 09:15 AM',
  },
  {
    id: '#1018',
    subject: 'Application crashes on startup',
    customer: 'Arun Kumar',
    customerEmail: 'arun.k@devstudio.io',
    agent: 'Alex Johnson',
    category: 'Technical Support',
    priority: 'Critical',
    status: 'In Progress',
    sla: '18 min remaining',
    updated: '4 min ago',
    created: 'Today, 08:45 AM',
  },
  {
    id: '#1015',
    subject: 'Password reset issue',
    customer: 'Meera Iyer',
    customerEmail: 'meera.i@designco.com',
    agent: 'Daniel Thomas',
    category: 'Account & Access',
    priority: 'Low',
    status: 'Open',
    sla: '5h remaining',
    updated: '1 hour ago',
    created: 'Yesterday, 04:20 PM',
  },
  {
    id: '#1009',
    subject: 'Unable to complete payment process',
    customer: 'Vikram Singh',
    customerEmail: 'vikram@enterprises.com',
    agent: 'Sarah Wilson',
    category: 'Billing',
    priority: 'High',
    status: 'Waiting for Customer',
    sla: 'At Risk (12m left)',
    updated: '2 hours ago',
    created: 'Yesterday, 02:10 PM',
  },
];

export const adminAllTickets = [
  ...adminRecentTickets,
  {
    id: '#1023',
    subject: 'Email notifications not sending',
    customer: 'David Wright',
    customerEmail: 'david.w@techcorp.com',
    agent: 'Michael Chang',
    category: 'Infrastructure',
    priority: 'Medium',
    status: 'In Progress',
    sla: '1h 30m remaining',
    updated: '30 min ago',
    created: 'Today, 09:40 AM',
  },
  {
    id: '#1022',
    subject: 'API Gateway 504 Gateway Timeout',
    customer: 'DevOps Team',
    customerEmail: 'devops@cloudservices.io',
    agent: 'Elena Rostova',
    category: 'Infrastructure',
    priority: 'Critical',
    status: 'Open',
    sla: '45 min remaining',
    updated: '40 min ago',
    created: 'Today, 09:20 AM',
  },
  {
    id: '#1020',
    subject: 'Bulk CSV export fails on 10k rows',
    customer: 'Data Analytics Co',
    customerEmail: 'analytics@dataco.org',
    agent: 'Unassigned',
    category: 'Bug Report',
    priority: 'Low',
    status: 'Open',
    sla: '6h remaining',
    updated: '2 hours ago',
    created: 'Today, 07:30 AM',
  },
  {
    id: '#1004',
    subject: 'Production login failure',
    customer: 'Enterprise Client Inc',
    customerEmail: 'admin@enterprise.com',
    agent: 'Alex Johnson',
    category: 'Technical Support',
    priority: 'Critical',
    status: 'In Progress',
    sla: 'Breached (15m ago)',
    updated: '10 min ago',
    created: 'Yesterday, 11:00 AM',
  },
];

export const adminUsersList = [
  {
    id: 'usr_101',
    name: 'Rahul Sharma',
    email: 'rahul.sharma@company.com',
    phone: '+1 (555) 123-4567',
    ticketsCount: 12,
    openTickets: 2,
    status: 'Active',
    joinedDate: 'Aug 12, 2026',
    lastActive: 'Today, 10:45 AM',
  },
  {
    id: 'usr_102',
    name: 'Anjali Menon',
    email: 'anjali@paytech.com',
    phone: '+1 (555) 234-5678',
    ticketsCount: 8,
    openTickets: 1,
    status: 'Active',
    joinedDate: 'Sep 01, 2026',
    lastActive: 'Today, 09:18 AM',
  },
  {
    id: 'usr_103',
    name: 'Arun Kumar',
    email: 'arun.k@devstudio.io',
    phone: '+1 (555) 345-6789',
    ticketsCount: 15,
    openTickets: 3,
    status: 'Active',
    joinedDate: 'Jul 24, 2026',
    lastActive: 'Today, 08:50 AM',
  },
  {
    id: 'usr_104',
    name: 'Meera Iyer',
    email: 'meera.i@designco.com',
    phone: '+1 (555) 456-7890',
    ticketsCount: 4,
    openTickets: 1,
    status: 'Active',
    joinedDate: 'Aug 29, 2026',
    lastActive: 'Yesterday',
  },
  {
    id: 'usr_105',
    name: 'Vikram Singh',
    email: 'vikram@enterprises.com',
    phone: '+1 (555) 567-8901',
    ticketsCount: 22,
    openTickets: 1,
    status: 'Active',
    joinedDate: 'Jun 15, 2026',
    lastActive: 'Yesterday',
  },
  {
    id: 'usr_106',
    name: 'Jessica Taylor',
    email: 'jtaylor@legacytech.com',
    phone: '+1 (555) 678-9012',
    ticketsCount: 0,
    openTickets: 0,
    status: 'Inactive',
    joinedDate: 'May 10, 2026',
    lastActive: '30 days ago',
  },
];

export const adminAgentsList = [
  {
    id: 'agt_201',
    name: 'Alex Johnson',
    email: 'alex.johnson@supportdesk.com',
    role: 'Support Agent',
    department: 'Tier 2 Technical Support',
    status: 'Available',
    assigned: 24,
    inProgress: 7,
    resolved: 18,
    sla: '96%',
    joinedDate: 'Jan 15, 2025',
  },
  {
    id: 'agt_202',
    name: 'Sarah Wilson',
    email: 'sarah.wilson@supportdesk.com',
    role: 'Support Agent',
    department: 'Billing & Payments',
    status: 'Busy',
    assigned: 21,
    inProgress: 6,
    resolved: 17,
    sla: '94%',
    joinedDate: 'Mar 10, 2025',
  },
  {
    id: 'agt_203',
    name: 'Daniel Thomas',
    email: 'daniel.thomas@supportdesk.com',
    role: 'Support Agent',
    department: 'Account Security',
    status: 'Available',
    assigned: 19,
    inProgress: 5,
    resolved: 15,
    sla: '91%',
    joinedDate: 'Apr 22, 2025',
  },
  {
    id: 'agt_204',
    name: 'Michael Chang',
    email: 'michael.chang@supportdesk.com',
    role: 'Support Agent',
    department: 'Infrastructure & DevOps',
    status: 'Away',
    assigned: 18,
    inProgress: 4,
    resolved: 14,
    sla: '98%',
    joinedDate: 'Jun 05, 2025',
  },
  {
    id: 'agt_205',
    name: 'Elena Rostova',
    email: 'elena.rostova@supportdesk.com',
    role: 'Support Agent',
    department: 'Integrations & API',
    status: 'Offline',
    assigned: 15,
    inProgress: 3,
    resolved: 12,
    sla: '95%',
    joinedDate: 'Aug 18, 2025',
  },
];

export const adminCategoriesList = [
  {
    id: 'cat_1',
    name: 'Technical Support',
    description: 'Hardware, software crashes, system errors, and performance issues.',
    ticketsCount: 412,
    status: 'Active',
    createdDate: 'Jan 10, 2025',
    icon: 'wrench',
  },
  {
    id: 'cat_2',
    name: 'Account & Access',
    description: 'Password resets, 2FA locks, SSO configuration, and role permissions.',
    ticketsCount: 328,
    status: 'Active',
    createdDate: 'Jan 10, 2025',
    icon: 'user-check',
  },
  {
    id: 'cat_3',
    name: 'Billing',
    description: 'Invoices, plan upgrades, subscription renewals, and tax receipts.',
    ticketsCount: 215,
    status: 'Active',
    createdDate: 'Jan 12, 2025',
    icon: 'file-text',
  },
  {
    id: 'cat_4',
    name: 'Payments',
    description: 'Credit card failures, payment gateway errors, and refund requests.',
    ticketsCount: 142,
    status: 'Active',
    createdDate: 'Jan 12, 2025',
    icon: 'credit-card',
  },
  {
    id: 'cat_5',
    name: 'Feature Request',
    description: 'Customer enhancement requests, product ideas, and roadmap suggestions.',
    ticketsCount: 88,
    status: 'Active',
    createdDate: 'Feb 01, 2025',
    icon: 'lightbulb',
  },
  {
    id: 'cat_6',
    name: 'Bug Report',
    description: 'UI glitches, API unexpected returns, and reproducible software bugs.',
    ticketsCount: 110,
    status: 'Active',
    createdDate: 'Feb 01, 2025',
    icon: 'bug',
  },
  {
    id: 'cat_7',
    name: 'Infrastructure',
    description: 'Server uptime, database connection limits, and CDN cache purges.',
    ticketsCount: 65,
    status: 'Active',
    createdDate: 'Mar 15, 2025',
    icon: 'server',
  },
  {
    id: 'cat_8',
    name: 'Legacy Migration',
    description: 'Deprecated API endpoints and data export migrations.',
    ticketsCount: 12,
    status: 'Inactive',
    createdDate: 'Apr 02, 2025',
    icon: 'archive',
  },
];

export const adminSlaPoliciesList = [
  {
    id: 'sla_1',
    policyName: 'Critical Priority SLA',
    priority: 'Critical',
    firstResponseTime: '15 min',
    resolutionTarget: '2 hours',
    businessHours: '24/7 Coverage',
    status: 'Active',
    withinSLA: 26,
    atRisk: 1,
    breached: 1,
  },
  {
    id: 'sla_2',
    policyName: 'High Priority SLA',
    priority: 'High',
    firstResponseTime: '1 hour',
    resolutionTarget: '8 hours',
    businessHours: 'Business Hours (9-6)',
    status: 'Active',
    withinSLA: 135,
    atRisk: 5,
    breached: 2,
  },
  {
    id: 'sla_3',
    policyName: 'Medium Priority SLA',
    priority: 'Medium',
    firstResponseTime: '4 hours',
    resolutionTarget: '24 hours',
    businessHours: 'Business Hours (9-6)',
    status: 'Active',
    withinSLA: 512,
    atRisk: 6,
    breached: 2,
  },
  {
    id: 'sla_4',
    policyName: 'Low Priority SLA',
    priority: 'Low',
    firstResponseTime: '8 hours',
    resolutionTarget: '72 hours',
    businessHours: 'Business Hours (9-6)',
    status: 'Active',
    withinSLA: 550,
    atRisk: 6,
    breached: 2,
  },
];

export const adminReportsSummary = {
  avgResolutionTime: '3h 45m',
  avgFirstResponse: '24 min',
  resolutionRate: '94.2%',
  reopenRate: '2.1%',
  categoryBreakdown: [
    { category: 'Technical Support', count: 412, percent: 33 },
    { category: 'Account & Access', count: 328, percent: 26 },
    { category: 'Billing', count: 215, percent: 17 },
    { category: 'Payments', count: 142, percent: 11 },
    { category: 'Bug Report', count: 110, percent: 9 },
    { category: 'Other', count: 41, percent: 4 },
  ],
};

export const adminSettingsData = {
  general: {
    companyName: 'SupportDesk Global Systems',
    supportEmail: 'support@supportdesk.com',
    timezone: 'UTC +05:30 (Asia/Kolkata)',
    defaultLanguage: 'English (US)',
  },
  ticketSettings: {
    allowCustomerReopen: true,
    requireCategory: true,
    allowAttachments: true,
    autoCloseResolvedDays: 3,
    defaultPriority: 'Medium',
  },
  notifications: {
    newTicketAlert: true,
    assignmentAlert: true,
    customerReplyAlert: true,
    slaWarningAlert: true,
    slaBreachAlert: true,
    escalationAlert: true,
    dailyReportEmail: true,
  },
  security: {
    sessionTimeoutMins: 30,
    passwordPolicy: 'Strong (Min 8 chars, numbers, symbols)',
    twoFactorAuth: 'Optional',
    loginAlerts: true,
  },
  appearance: {
    theme: 'Dark Navy (Default)',
    compactMode: false,
    sidebarBehavior: 'Expanded',
  },
};
