import KnowledgeArticle from '../../models/KnowledgeArticle.js';
import User from '../../models/User.js';

const SEED_ARTICLES = [
  {
    title: 'Getting Started with SupportDesk',
    category: 'Getting Started',
    content: `Welcome to SupportDesk! This guide helps you navigate the core features of our ticketing platform.

1. Account Setup
Make sure your profile information is up to date in the Settings tab. Ensure you have verified your email address.

2. Creating Your First Ticket
Navigate to the "Create Ticket" page from your customer navigation bar. Choose the relevant category, give a clear subject, and provide detailed steps to reproduce any issue you are facing.

3. Tracking Ticket Status
Your tickets can be in one of four states: Open, In Progress, Resolved, or Closed. You will receive real-time notifications whenever an agent updates your ticket.

4. Communication
You can reply directly to any ticket from the ticket details view. Keep discussions focused on the issue for faster resolution.`,
    status: 'PUBLISHED',
  },
  {
    title: 'How to Set Up Two-Factor Authentication (2FA)',
    category: 'Account & Security',
    content: `Two-factor authentication adds an extra layer of security to your SupportDesk account.

Why Enable 2FA?
Passwords can be compromised through phishing or data breaches. 2FA ensures that only you can access your account even if someone discovers your password.

Steps to Enable:
1. Go to Profile > Security Settings.
2. Select "Enable Two-Factor Authentication".
3. Use an authenticator app (such as Google Authenticator, Authy, or 1Password) to scan the QR code.
4. Enter the 6-digit confirmation code generated by your app.
5. Save your backup recovery codes in a secure password manager.`,
    status: 'PUBLISHED',
  },
  {
    title: 'Managing Your Subscription & Invoicing',
    category: 'Billing & Plans',
    content: `Learn how to manage your organization's subscription tier, billing contact, and payment history.

Billing Cycle
Subscriptions are billed either monthly or annually depending on your chosen plan. Receipts are automatically sent to the registered billing email address.

Upgrading or Downgrading
You can change your subscription plan at any time from your account settings. Upgrades take effect immediately with prorated charges, while downgrades take effect at the end of the current billing period.

Viewing Invoices
All past invoices and tax receipts are available for download in PDF format under the Invoices tab in Settings.`,
    status: 'PUBLISHED',
  },
  {
    title: 'Troubleshooting Common Email Delivery Issues',
    category: 'Troubleshooting',
    content: `If you are not receiving ticket notifications or reset emails, follow these diagnostic steps.

1. Check Spam and Junk Folders
Automated notification emails may occasionally be classified as spam. Check your junk folder and mark SupportDesk emails as "Not Spam".

2. Whitelist SupportDesk Domains
Ask your IT department to whitelist emails coming from @supportdesk.io and ensure your mail server does not block inbound notifications.

3. Verify Email Address in Profile
Double-check that the email address associated with your profile is spelled correctly and active.`,
    status: 'PUBLISHED',
  },
  {
    title: 'Configuring Webhooks and REST API Integrations',
    category: 'API & Integrations',
    content: `SupportDesk provides RESTful APIs and real-time Webhooks to seamlessly integrate with your existing CRM, Slack, or internal tooling.

API Keys
Generate an API token from Settings > API Keys. Keep your keys secret and rotate them regularly. All requests require a Bearer token in the Authorization header.

Webhook Events
Subscribe to ticket lifecycle events:
- ticket.created
- ticket.status_changed
- ticket.comment_added
- ticket.assigned

Payloads are sent as JSON with cryptographic HMAC signatures for verification.`,
    status: 'PUBLISHED',
  },
  {
    title: 'Understanding Ticket Priority and SLA Timelines',
    category: 'General',
    content: `Our support team prioritizes requests based on impact, urgency, and customer SLA tiers.

Priority Levels:
- Low: General inquiries, cosmetic issues, minor feature suggestions. Target response within 24 hours.
- Medium: Functional issues with available workarounds. Target response within 8 hours.
- High: Core workflow impacted with significant business disruption. Target response within 4 hours.
- Urgent: Complete system outage or critical security vulnerability. Target response within 1 hour.`,
    status: 'PUBLISHED',
  },
];

export const seedKnowledgeBaseIfEmpty = async () => {
  const count = await KnowledgeArticle.countDocuments();
  if (count === 0) {
    // Find an admin user or any user to assign as author
    let author = await User.findOne({ role: 'admin' });
    if (!author) {
      author = await User.findOne();
    }

    if (author) {
      const articlesToInsert = SEED_ARTICLES.map((art) => ({
        ...art,
        authorId: author._id,
      }));
      await KnowledgeArticle.insertMany(articlesToInsert);
    }
  }
};

export const getArticles = async ({
  search = '',
  category = '',
  status = '',
  page = 1,
  limit = 20,
  userRole = 'customer',
}) => {
  await seedKnowledgeBaseIfEmpty();

  const query = {};

  // RBAC enforcement: non-admins can only see PUBLISHED articles
  if (userRole !== 'admin') {
    query.status = 'PUBLISHED';
  } else if (status && status !== 'ALL') {
    query.status = status;
  }

  // Category filter
  if (category && category !== 'all' && category !== 'ALL') {
    query.category = category;
  }

  // Keyword search across title and content
  if (search && search.trim()) {
    const trimmed = search.trim();
    query.$or = [
      { title: { $regex: trimmed, $options: 'i' } },
      { content: { $regex: trimmed, $options: 'i' } },
      { category: { $regex: trimmed, $options: 'i' } },
    ];
  }

  const pageNum = Math.max(1, parseInt(page, 10) || 1);
  const limitNum = Math.min(100, Math.max(1, parseInt(limit, 10) || 20));
  const skip = (pageNum - 1) * limitNum;

  const [articles, total] = await Promise.all([
    KnowledgeArticle.find(query)
      .populate('authorId', 'name email role')
      .sort({ createdAt: -1 })
      .skip(skip)
      .limit(limitNum)
      .lean(),
    KnowledgeArticle.countDocuments(query),
  ]);

  const totalPages = Math.ceil(total / limitNum) || 1;

  return {
    articles,
    pagination: {
      page: pageNum,
      limit: limitNum,
      total,
      totalPages,
      hasNextPage: pageNum < totalPages,
      hasPreviousPage: pageNum > 1,
    },
  };
};
